[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [".git", "__pycache__", "build", "dist", "*/tests/*", ".pixi/*"]

[tool.ruff.lint]
select = ["E", "F", "I"]
unfixable = ["F401"]

[tool.pyright]
exclude = [".pixi/*", ".venv/*"]
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
